# CraftBook Configuration for Bukkit. Generated for version: 5.0.0-SNAPSHOT;4156677
# This configuration will automatically add new configuration options for you,
# So there is no need to regenerate this configuration unless you need to.
# More information about these features are available at...
# https://craftbook.enginehub.org/en/latest//Usage
#
# NOTE! NOTHING IS ENABLED BY DEFAULT! ENABLE FEATURES TO USE THEM!


# List of mechanics and whether they are enabled or not
mechanics:
  general:
    AI: false
    BetterLeads: false
    BetterPhysics: false
    BetterPistons: false
    BetterPlants: false
    Bookcase: false
    BounceBlocks: false
    Bridge: false
    Chairs: false
    ChunkAnchor: false
    CommandSigns: false
    CookingPot: false
    DispenserRecipes: false
    Door: false
    Elevator: false
    Gate: false
    HeadDrops: false
    HiddenSwitch: false
    LightSwitch: false
    MapChanger: false
    Marquee: false
    PaintingSwitcher: false
    Snow: false
    Sponge: false
    Teleporter: false
    ToggleArea: false
    TreeLopper: false
    Variables: true
    XPStorer: false
  tool:
    Ammeter: false
    LightStone: false
    SignCopier: false
  boat:
    BoatDecay: false
    BoatDrops: false
    BoatExitRemover: false
    BoatRemoveEntities: false
    BoatSpeedModifiers: false
    BoatUncrashable: false
    BoatWaterPlaceOnly: false
    LandBoats: false
  customisation:
    Cauldron: false
    CommandItems: false
    CustomCrafting: false
    CustomDrops: false
    LegacyCauldron: false
  circuit:
    Glowstone: false
    ICs: false
    JackOLantern: false
    Jukebox: false
    Netherrack: false
    Pay: false
    Pipes: false
  minecart:
    MinecartBooster: false
    MinecartCollisionEntry: false
    MinecartConstantSpeed: false
    MinecartDecay: false
    MinecartDeposit: false
    MinecartDispenser: false
    MinecartEjector: false
    MinecartElevator: false
    MinecartEmptySlowdown: false
    MinecartExitRemover: false
    MinecartFallModifier: false
    MinecartItemPickup: false
    MinecartMaxSpeed: false
    MinecartMessenger: false
    MinecartMobBlocker: false
    MinecartMoreRails: false
    MinecartNoCollide: false
    MinecartPlaceAnywhere: false
    MinecartRailPlacer: false
    MinecartRemoveEntities: false
    MinecartReverser: false
    MinecartSorter: false
    MinecartSpeedModifiers: false
    MinecartStation: false
    MinecartTeleporter: false
    MinecartTemporaryCart: false
    MinecartVisionSteering: false

# WARNING! Changing this can result in all ST mechanics acting very weirdly, only change this if you know what you are doing!
st-think-ticks: 2

# Causes many mechanics to require sufficient blocks to function, for example gates, bridges and doors.
safe-destruction: true

# If on, OP's will not default to have access to everything.
no-op-permissions: false

# Allows redstone not directly facing a mechanism to trigger said mechanism.
indirect-redstone: false

# Rounds all distance equations to the block grid.
use-block-distance: false

# Checks to see if WorldGuard allows building/using in the area when activating mechanics.
check-worldguard-flags: true

# Use advanced methods to detect if a player can build or not. Use this if you use region protections other than WorldGuard, or experience issues with WorldGuard protection. This can add extra entries to Block Logging plugins when a mechanic is broken/placed.
advanced-block-checks: true

# In conjunction with advanced-block-checks, this option adds a few extra checks if you are experiencing compatibility issues with certain plugins that stop breaks/places/interacts.
pedantic-block-checks: false

# Make sure a player can only press signs so often.
sign-click-timeout: 10

# The default language for CraftBook. Note: This language needs to be in the 'languages' field for this to work.
language: en_US

# A list of languages supported by craftbook, if a user requests a language not listed... They will see default.
languages:
  - en_US

# If enabled, CraftBook will scan messages sent to players for localizable text, instead of just checking if the entire message is localizable.
scan-text-for-localization: false

# Enable a mode that will print extra debug information to the console.
debug-mode: false

# Causes all debug mode output to be logged into a file. This file is reset every startup (And every /cb reload).
debug-mode-file-logging: false

# Enable certain debug types when debug mode is enabled.
debug-flags: []

# Show messages when a player does not have permission to do something.
show-permission-messages: true

# PersistentStorage stores data that can be accessed across server restart. Method of PersistentStorage storage (Note: DUMMY is practically off, and may cause issues). Can currently be any of the following: YAML, DUMMY, SQLite
persistent-storage-type: YAML

# Causes mechanics to attempt to convert names to use CBIDs. This can and should be disabled after you believe your servers transition to UUIDs v Names is complete.
convert-names-to-cbids: false
